### ISSUE TITLE
That is no Albatross!

### ISSUE THREAD

**Issue by magnus-hansson** [Kunskapslyftet/orange-albatross#1]
Need to change pic, pull request inc

**Comment by johan-mattsson** [comment]
Det är det visst!!!! Kolla här:
https://www.google.com/search?q=orange+albatross&espv=2&biw=1497&bih=927&site=webhp&source=lnms&tbm=isch&sa=X&ei=aZ_0VOHANcrbUcmygtgJ&ved=0CAYQ_AUoAQ

**Comment by magnus-hansson** [comment]
Okay, vi stänger den här issuen då.
